; RUN: llc -O2 -o - %S/load.ll -stop-after=if-converter | FileCheck %s
; CHECK: LBZri10
; CHECK: LBZri10
; CHECK: LBZri37
; CHECK: LBZri37
; CHECK: LBZri64
; CHECK: LBZri64
; CHECK: LBZri64
; CHECK: LBZri64
; CHECK: LWZrrc
; CHECK: LDrrc
; CHECK: LWZri10
; CHECK: LDrrc
; CHECK: LWZrrc
; CHECK: LDrrc
; CHECK: LWZrrc
; CHECK: LDrrc
; CHECK: LWZrrc
; CHECK: LDrrc
; CHECK: LWZrrc
; CHECK: LDrrc
; CHECK: LWZrrc
; CHECK: LDrrc
; CHECK: LWZrrc
; CHECK: LDrrc
; CHECK: LBZrrc
; CHECK: LBZri27c
; CHECK: LBZri27c
; CHECK: LBZri27c
; CHECK: LBZri27c
; CHECK: LBZri54c
; CHECK: LBZri54c
; CHECK: LBZri64
; CHECK: LBZri64
; CHECK: LWSrrc
; CHECK: LQrrc
; CHECK: LOrrc
; CHECK: LOri10
